### PR TITLE
Feature/add extra events

### PR DESCRIPTION
**Pull request by oviolion**

### CODE REVIEW

**Comment by oviolion** [comment]
@polishq can you take a look over this one as well please? It's the one we've talked about a few weeks earlier

**Comment by polishq** [comment]
@oviolion We'll need to merge https://github.com/vtex-apps/klaviyo-pixel/pull/14 and then rebase this branch before this PR can be merged. Please review my updates on that PR and let me know if it's okay to publish.

**Comment by oviolion** [comment]
> @oviolion We'll need to merge #14 and then rebase this branch before this PR can be merged. Please review my updates on that PR and let me know if it's okay to publish.

@polishq I'm alright with the updates on the other PR 🚀
Let me know when you're okay with publishing them

**Comment by oviolion** [comment]
> @oviolion #14 has been merged. Please rebase this branch and I'll proceed with the review.

Thank you @polishq, I have updated it.

**Review by polishq — APPROVED** [review]

**Pull request merged**
